name: Update Version

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Update branch version by:'
        type: choice
        options:
          - major
          - minor
          - patch
        required: true
        default: 'patch'

env:
  ALLOW_UPDATES: ${{ startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/hotfix/') }}

jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ env.version_tag }}
      previous_version_tag: ${{ env.previous_version_tag }}

    steps:
    - name: Check For Valid Updates
      if: env.ALLOW_UPDATES == false
      run: |
        echo "Version updates should only be done on development or hotfix"
        exit 1

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Nerdbank.GitVersioning tool
      run: dotnet tool install --global nbgv

    - name: Get Previous Version
      id: get_previous_version
      run: |
        nbgv get-version --format json > nbgv.json
        previous_version=$(jq -r .NuGetPackageVersion nbgv.json)
        echo "previous_version_tag=$previous_version" >> $GITHUB_ENV

    - name: Bump Version
      run: |
        nbgv set-version ${{ github.event.inputs.version_type }}

    - name: Get New Version
      id: get_new_version
      run: |
        nbgv get-version --format json > nbgv.json
        new_version=$(jq -r .NuGetPackageVersion nbgv.json)
        echo "version_tag=$new_version" >> $GITHUB_ENV

    - name: Commit and Push Version Change
      run: |
        git config --global user.name '${{ github.triggering_actor }}'
        git config --global user.email '${{ github.triggering_actor }}@users.noreply.github.com'
        git add version.json
        git commit -m "Bump version: ${{ env.previous_version_tag }} → ${{ env.version_tag }}"
        git push